version: '3.6'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Book_Server
      POSTGRES_USER: fahim
      POSTGRES_PASSWORD: 50569
    ports:
      - "5432:5432"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://fahim:50569@localhost/Book_Server
    ports:
      - "80:80"
    networks:
      - app-network

