version: '3.6'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: <Database_Name>
      POSTGRES_USER: <user_name>
      POSTGRES_PASSWORD: 50569
    ports:
      - "5432:5432"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://<user>:<password>@localhost/<Database_Name>
    ports:
      - "80:80"
    networks:
      - app-network

